services:
  - type: web
    name: deogiri-canteen
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        sync: false
      - key: SESSION_SECRET
        generateValue: true
